apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: 514010966842.dkr.ecr.us-west-2.amazonaws.com/demo-reg:latest
          imagePullPolicy: Always
          name: demo
          command: ["sh", "-c"]
          args:
          - while true; do
              echo -en '\n';
              printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
              printenv MY_POD_IP;
              sleep 20;
              /root/create.index.sh;
              /usr/sbin/apachectl start;
            done;

          env:         
            - name: MY_NODE_NAME           
              valueFrom:             
                 fieldRef:               
                   fieldPath: spec.nodeName
            - name: MY_POD_NAME           
              valueFrom:             
                 fieldRef:               
                   fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:             
                 fieldRef:               
                   fieldPath: metadata.namespace 
            - name: MY_POD_IP           
              valueFrom:             
                 fieldRef:               
                   fieldPath: status.podIP 
          ports:
            - containerPort: 80 
            - containerPort: 443 
